# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TenUp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TenUp
  pod 'react-native-camera', path: '../node_modules/react-native-camera'



  target 'TenUpTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TenUp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TenUp-tvOS

  target 'TenUp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
